# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCloudMusic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCloudMusic
  pod 'Moya', '~> 14.0.0-alpha.1'
  pod 'MBProgressHUD', '~> 1.1.0'
  
end
